### PR TITLE
Updated the CFP

### PR DESCRIPTION
**Pull request by phkrief**
Signed-off-by: Philippe Krief <philippe.krief@eclipse-foundation.org>

### CODE REVIEW

**Comment by phkrief** [comment]
@chrisguindon I forgot to update the CFP. Could you merge this update asap? Thx a lot for your help

**Comment by phkrief** [comment]
Hi @chrisguindon I don't understand what happened with this PR. I updated the CFP file but when I try it on the website I still get the old version. 
I have the feeling that because the file name was the same Hugo didn't update the file. Any idea? Thx a lot

**Comment by chrisguindon** [comment]
It's possible, we are having issues with our infra. I will take a look.

**Comment by chrisguindon** [comment]
@phkrief,

I just took a look and the job for deploying the site is currently stalled. It's been running for  1 day 1 hr. I will stop if and start a new one.

**Comment by chrisguindon** [comment]
@mbarbero,

I was able to start a new build however, I don't see to be able to remove the job that is stalled:
https://foundation.eclipse.org/ci/webdev/job/events.eclipse.org/job/master/191/

Can you help here?

**Comment by mbarbero** [comment]
> I was able to start a new build, however, I am not able to remove the stalled job:
> https://foundation.eclipse.org/ci/webdev/job/events.eclipse.org/job/master/191/

This one was stuck because of some issues on the build cluster. I've cleaned up the stale state.

**Comment by chrisguindon** [comment]
Thanks @mbarbero !

**Pull request merged**
