### PR TITLE
Add a "Research" Category in the events main page #179

### PR DESCRIPTION
**Pull request by chrisguindon**
Signed-off-by: Christopher Guindon <chris.guindon@eclipse-foundation.org>

### CODE REVIEW

**Comment by chrisguindon** [comment]
@flora8984461 I made some updates to some of your tests as they are falling!

**Comment by flora8984461** [comment]
Cool, thanks, I'll check it. But I think we should need to add this category in backend as well? So the fetched event data has some events with type "research"

**Comment by chrisguindon** [comment]
@flora8984461 I already did that part! You should be able to test it in the preview.

**Comment by flora8984461** [comment]
The failing tests are caused by date time checks. 

I directly used js builtin `toLocaleDateString` which automatically generates `AM` ,`PM`, and `Tue` without `.` . Which is different as you changed the expected.

(reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleTimeString)

If you hope to use lowercase, and add a '.' after abbrev after weekdays, I can make the changes.

**Pull request merged**
