### PR TITLE
Initial copy for the SAAM Mobility site

### PR DESCRIPTION
**Pull request by autumnfound**
Signed-off-by: Martin Lowe <martin.lowe@eclipse-foundation.org>

### CODE REVIEW

**Comment by sjkiwai** [comment]
Rev5 Background SAAM Mobility
Rev5 SAAM Mobility

**Comment by autumnfound** [comment]
@sjkiwai it doesn't look like there's an easy way to update the jumbotron on a page by page basis, so we'll add a request to add this as a feature in our events framework

**Comment by autumnfound** [comment]
I've also removed the sample content, so if you're happy with the starting content, we can merge this in!

**Comment by sjkiwai** [comment]
Thank you, Martin!

**Comment by chrisguindon** [comment]
I made a small tweak to fix the date on https://deploy-preview-171--eclipsefdn-events.netlify.app/2021/

@sjkiwai before we merge, can you confirm that the registration link is correct? https://www.crowdcast.io/e/aduh2zba

Seems wrong to be linking to JakartaOne Livestream - Japan..

**Comment by sjkiwai** [comment]
@chrisguindon - thanks for finding that. The registration button should be Call for Papers with a link to this doc. 
[Uploading CfP-SAAM-V1.1.pdf…]()

**Comment by chrisguindon** [comment]
@sjkiwai your link does not work.

**Comment by sjkiwai** [comment]
This looks great. Just one small correction and one addition and in fact, I think we have our 'save the date' page! 
- Please add "Eclipse" before the SAAM Mobility title => Eclipse SAAM Mobility 2021 
- dates should be Jun 15-16.  (I think this was already in a commit from Martin but I'm not sure.

**Comment by sjkiwai** [comment]
Looks great! +1 for merging
And, thank you!

**Comment by phkrief** [comment]
@autumnfound , @chrisguindon could you plan to add the capability to its own jumbotron? It will be great. 
Should we create a bug against the solstice theme?
Thx

**Comment by chrisguindon** [comment]
@phkrief do you mean that you want to create a custom image for the jumbotron of this event?

**Comment by phkrief** [comment]
Yes, this is the idea. 
We want to have an image adapted to the topic of the event. This time it is mobility. 

⁣Kind regards
—
Philippe Krief, PhD
Research Relations Director | Eclipse Foundation, Inc.
Eclipse Foundation: The Platform for Open Innovation and Collaboration
M: +33 (0)6 21 01 06 81 
Annastr. 46, 
D-64673 Zwingenberg
Handelsregister: Darmstadt HRB 92821Managing Directors: Gaël Blondelle, Mike Milinkovich ​

Le 13 févr. 2021 à 00:25, à 00:25, Christopher Guindon <notifications@github.com> a écrit:

**Comment by chrisguindon** [comment]
@phkrief We already support this feature but we need someone the create the image before we can add it to the site.

I would recommend reaching out to our Creative Lead, @meKokabi to design a new background image for your event.

Once that is done, feel free to create an issue asking us to update the jumbotron image for your event. Someone on the webdev team will be able to make that change for you!

**Comment by phkrief** [comment]
In this case, could you use this banner or do you need a better resolution?
banniere-eclipse-sans-texte

**Comment by chrisguindon** [comment]
@phkrief we can start with that and let you know if there is any issues.


Would you mind creating a new issue for this request? This PR is now closed!

**Pull request merged**
