### PR TITLE
update banner for SAAM 2021

### LINKED ISSUE #175: Eclipse SAAM Mobility 2021 Banner
Could you have the kindness to replace the default banner of the SAAM Mobility event with the attached file?
Thx a lot
banniere-eclipse-sans-texte

### PR DESCRIPTION
**Pull request by flora8984461**
Fix #175 

Signed-off-by: Yi Liu <yi.liu@eclipse-foundation.org>

### CODE REVIEW

**Comment by autumnfound** [comment]
The image looks a bit pixelated, did you compress it? We can leave banner images a little larger in file size than other images on the site since they are more central and larger than other images

**Comment by flora8984461** [comment]
> The image looks a bit pixelated, did you compress it? We can leave banner images a little larger in file size than other images on the site since they are more central and larger than other images

Yes, the original one has 1060kb. I scaled the size to half and also used online compress. 

I updated it only using online compress. Not sure if this one is okay? 

Or should I not use online compress but just scale the size?

**Comment by autumnfound** [comment]
> > The image looks a bit pixelated, did you compress it? We can leave banner images a little larger in file size than other images on the site since they are more central and larger than other images
> 
> Yes, the original one has 1060kb. I scaled the size to half and also used online compress.
> 
> I updated it only using online compress. Not sure if this one is okay?
> 
> Or should I not use online compress but just scale the size?

Generally, we want to make sure its not much larger than our largest breakpoint, 1920 is fine for most devices, 2560 for a little bit  of future proof (retina + ultrawide). Any larger than that isn't useful. You should be able to compress easily enough through a program like photoshop or gimp though. Compression is fine, we just aim to compress it just before the quality degrades noticeably (seeing artifacting, or loss of sharpness). 100kb is a fine size for a banner!

**Review by autumnfound — APPROVED** [review]

**Comment by phkrief** [comment]
@flora8984461 how are you progressing on this PR?
Did you notice the issue https://github.com/EclipseFdn/events.eclipse.org/issues/175 ?
If you prefer that I resize the files to a good size, please let me know.
Thx a lot

**Comment by flora8984461** [comment]
> @flora8984461 how are you progressing on this PR?
> Did you notice the issue #175 ?
> If you prefer that I resize the files to a good size, please let me know.
> Thx a lot

Hi @phkrief , Thanks for your reminder, and I am so sorry for the late reply!

I just replied on https://github.com/EclipseFdn/events.eclipse.org/issues/175#issuecomment-785104748. Would you mind giving me some advice on which one you decide to use? Thanks!

BTW, I think the size is good.

**Comment by phkrief** [comment]
On which bug do you want I advice? On this one or on #175  ?

**Comment by phkrief** [comment]
For the header you could take:
header
for the middle dark sections, you could take:
middle-page-2

Does it make sense ?

**Comment by phkrief** [comment]
Actually we could improve the last one a little bit...
Gimme a sec

**Comment by flora8984461** [comment]
thanks! @phkrief

**Comment by phkrief** [comment]
We could either use this one:
image
and if it is not dark enough, we could use this one instead:
image

Does it help?

**Comment by flora8984461** [comment]
Hi @phkrief 
Please have a preview on the staging: https://deploy-preview-176--eclipsefdn-events.netlify.app/2021/saam-mobility/

Thanks!

**Comment by phkrief** [comment]
Personally, I like it! What about you? 
I also pinged @sjkiwai to have her feedback.
Let see...
Thanks a lot for your, as always, great work dear @flora8984461 !

**Comment by flora8984461** [comment]
@phkrief Thanks! Let me know when you like it to be merged to live after you confirm.

**Comment by sjkiwai** [comment]
The banner works well in the title and in the technical topics section. But when it gets bigger for the list of the TPC, it reminds me of a dark cellar. Maybe we can switch the TPC list to the light background?

**Comment by phkrief** [comment]
Makes sense, @sjkiwai ! I will see where I can add a section to switch to a light section for the TPC.
In meantime, @flora8984461 , could you push your code and merge it with my latest changes?
thx a lot

**Comment by flora8984461** [comment]
@phkrief Thx, sure, I will ask my team to help review and push this version. https://deploy-preview-176--eclipsefdn-events.netlify.app/2021/saam-mobility/
Thanks!

**Comment by chrisguindon** [comment]
I made a small update to this PR to allow us to use the new background image each time we use the .featured-section-row-dark-bg class on the saam-2021-event event: https://github.com/EclipseFdn/events.eclipse.org/pull/176/commits/238aec1d269d003c6e5dc1dab09b108d18edd318

**Pull request merged**
