### PR TITLE
Adding the Keynote section with the agenda

### PR DESCRIPTION
**Pull request by phkrief**
Signed-off-by: Philippe Krief <philippe.krief@eclipse-foundation.org>

### CODE REVIEW

**Comment by phkrief** [comment]
Hi @chrisguindon 
I try to add a "Keynote speakers" section to our page. 
I might be missing something because the section shows up but the pictures.
Can you help me?
Thx a lot

**Comment by chrisguindon** [comment]
@autumnfound Do you have a moment to take a look at this issue for @phkrief please?

**Comment by autumnfound** [comment]
@phkrief are you still having issues with this? Chris reached out as I missed this, but checking it out, it looks like you got this working?
image

**Comment by phkrief** [comment]
Yes I found my problem. Thx for asking

⁣Kind regards
—
Philippe Krief, PhD
Research Relations Director | Eclipse Foundation, Inc.
Eclipse Foundation: The Platform for Open Innovation and Collaboration
M: +33 (0)6 21 01 06 81 
Annastr. 46, 
D-64673 Zwingenberg
Handelsregister: Darmstadt HRB 92821Managing Directors: Gaël Blondelle, Mike Milinkovich ​

Le 12 mars 2021 à 19:53, à 19:53, Martin Lowe ***@***.***> a écrit:
***@***.*** are you still having issues with this? Chris reached out as I

**Comment by phkrief** [comment]
I forgot to send this comment:

@chrisguindon I found the issue: I was missing a file: keynote.yml file.
Btw, I have the feeling that this file is redundant with the speakers.yml file. Is it expected?
Actually, I have to duplicate the bio and the description of the keynote speakers on both files.

**Comment by chrisguindon** [comment]
@phkrief It's expected.

The idea is that you could create multiple lists of users on the site. They don't need to be keynotes or speakers. 

For example, you could use this component to list the Program Committee.

**Comment by phkrief** [comment]
Gotcha! Makes sense! Thx a lot

**Pull request merged**
