### PR TITLE
Susan/master/agendaiteration

### PR DESCRIPTION
**Pull request by sjkiwai**

### CODE REVIEW

**Comment by sjkiwai** [comment]
@chrisguindon Please review this update. Thank you!

**Comment by autumnfound** [comment]
@sjkiwai we actually have support for multi day agendas baked in, mind if I jump in and see if I can get that working?

**Comment by autumnfound** [comment]
Take a look at the preview and let me know if it still looks good, and we can merge it!

**Comment by sjkiwai** [comment]
Looks great! Thank you for doing this.

**Comment by sjkiwai** [comment]
@autumnfound Do you see these updates on the website?

**Comment by chrisguindon** [comment]
@sjkiwai The build failed.

@mbarbero,

I took a look and for some reason, the eclipsefdn/hugo-node:latest (https://hub.docker.com/layers/eclipsefdn/hugo-node/latest/images/sha256-c3017b0bf2748218649bb0b9bdb2c69fad68cd1dc9acda95f4d95b2cf45cc982?context=explore) is HUGO_VERSION=0.62.2  & NODE_VERSION=10.15.0 which is not supposed to be the latest..

However, we no longer support this version. We expect to build our sites with HUGO_VERSION=0.76.5 / NODE_VERSION=12.22.1  https://github.com/EclipseFdn/dockerfiles/blob/master/hugo-node/h0.76.5-n12.22.1/Dockerfile

The build.sh seems correct:
https://github.com/EclipseFdn/dockerfiles/blob/master/build.sh#L31

Do you know what could have caused this? This looks like a recent issue since the site was successfully built yesterday.

**Comment by mbarbero** [comment]
there is definitely something weird with this
```
docker run -it --rm docker.io/eclipsefdn/hugo-node:h0.76.5-n12.22.1 hugo version
Hugo Static Site Generator v0.62.2-83E50184 linux/amd64 BuildDate: 2020-01-05T18:51:38Z
```

**Comment by mbarbero** [comment]
https://github.com/EclipseFdn/dockerfiles/commit/ec573fb7a68873c36a90e8199b0913c9aabb744f should have fixed this.

**Comment by chrisguindon** [comment]
Thanks @mbarbero!

**Pull request merged**
