### PR TITLE
We had the restrict the TCP list

### PR DESCRIPTION
**Pull request by phkrief**
We had to retrict the list to the people who signed the EDAS.
If this PR is accepted, I will be able to update regularly this list.
Thx

Signed-off-by: Philippe Krief <philippe.krief@eclipse-foundation.org>

### CODE REVIEW

**Comment by phkrief** [comment]
I'm done for now with our changes.
@chrisguindon @autumnfound would you mind to review and publish them?
Thanks a lot

**Comment by chrisguindon** [comment]
Done! Thanks for the PR!

**Comment by phkrief** [comment]
Thank YOU, @chrisguindon !!! I respected the process you described us during our training session :-)...

**Comment by chrisguindon** [comment]
YW - You did an awesome job @phkrief!

**Pull request merged**
