### PR TITLE
New agenda updates

### PR DESCRIPTION
**Pull request by phkrief**
Finalizing Simone

Signed-off-by: Philippe Krief <philippe.krief@eclipse-foundation.org>

### CODE REVIEW

**Comment by phkrief** [comment]
Hi @ericpoirier 

Could you accept this new PR?
Thx a lot

**Comment by ericpoirier** [comment]
Hi Philippe, is this ready to be merged?

**Comment by phkrief** [comment]
Hi @ericpoirier 
Thx for asking.
Not this PR is not ready. We had a call this morning so I have tgo make some minor changes.
Thanks a lot

**Comment by phkrief** [comment]
Dear @ericpoirier ,
Ths PR is ready to go now.
Thanks a lot for accepting it

Kind regards

**Pull request merged**
