### PR TITLE
Render a React component with JSX

### PR DESCRIPTION
**Pull request by chrisguindon**
Signed-off-by: Christopher Guindon <chris.guindon@eclipse-foundation.org>

### CODE REVIEW

**Comment by chrisguindon** [comment]
I am thinking of creating a new branch to commit this PR. This new branch could be used as a starting point for implementing Refresh the events.eclipse.org homepage #15

**Review by flora8984461 — COMMENTED** [review]
Does it show anything on the event page for you? It is empty for me.
gives me error : Failed to load resource: the server responded with a status of 404 (Not Found)

🤔

**Comment by flora8984461** [comment]
> I am thinking of creating a new branch to commit this PR. This new branch could be used as a starting point for implementing Refresh the events.eclipse.org homepage #15

Yeah, we can do that.

**Comment by chrisguindon** [comment]
You can see a preview of this PR here: https://deploy-preview-86--eclipsefdn-events.netlify.app/

Those preview links are always available via the netlify/eclipsefdn-events/deploy-preview status link.

**Comment by chrisguindon** [comment]
Make sure to install the dependencies with npm install before starting the hugo server.

You can use npm run watch in another console to edit the js and make sure the code is re-compiled each time you save!

**Review by flora8984461 — APPROVED** [review]
this is a nice way

**Comment by chrisguindon** [comment]
> this is a nice way.
> I would like to investigate on if importing other libraries it also works unless I code everything from scratch

Importing libraries works exactly how you would expect it to work.

For example, in https://github.com/EclipseFdn/events.eclipse.org/pull/86/files#diff-69e21795a2d7817f1615f21ddc58c3d0R1, I'm importing my custom component called Event but I am also importing ReactDOM because it was added as a dependency in the package.json file: https://github.com/EclipseFdn/events.eclipse.org/pull/86/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R26

**Comment by flora8984461** [comment]
> > this is a nice way.
> > I would like to investigate on if importing other libraries it also works unless I code everything from scratch
> 
> Importing libraries works exactly how you would expect it to work.
> 
> For example, in https://github.com/EclipseFdn/events.eclipse.org/pull/86/files#diff-69e21795a2d7817f1615f21ddc58c3d0R1, I'm importing my custom component called Events + I am importing ReactDOM because it was added as a dependency in the package.json file: https://github.com/EclipseFdn/events.eclipse.org/pull/86/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R26

True, I just tried with other lib such as material-ui, it works.

**Pull request merged**
