### PR TITLE
Update to CN4EF Day website

### PR DESCRIPTION
**Pull request by linkfang**
Fixes [issue220](https://github.com/EclipseFdn/events.eclipse.org/issues/220)

### CODE REVIEW

**Comment by ericpoirier** [comment]
Hi Zhou, is this still a work in progress?

**Comment by linkfang** [comment]
> Hi Zhou, is this still a work in progress?

Yes, but just need to update the footer and the add background color.

**Comment by ericpoirier** [comment]
> > Hi Zhou, is this still a work in progress?
> 
> Yes, but just need to update the footer and the ad background color.

Ok sounds good, let me know when its ready to review.

**Comment by chrisguindon** [comment]
Screenshot 2021-09-09 112811


The text-shadow that I added to improve readability in the jumbotron is being included in our dropdown menu. We need to fix that.

**Comment by linkfang** [comment]
> 
> Ok sounds good, let me know when its ready to review.

Got +1 from Anne, ready for code review!

**Review by autumnfound — APPROVED** [review]

**Comment by autumnfound** [comment]
The code looks good. We have another 'here' link in the content, but that can be patched afterwards

**Review by ericpoirier — APPROVED** [review]

**Comment by ericpoirier** [comment]
Are we good to push this live?

**Pull request merged**
