### PR TITLE
Update theme to fix Double links on papers #131

### LINKED ISSUE #131: Double links on papers
**Describe the bug**
I wanted to complete the SAM-IoT agenda by adding the links to accepted papers. Knowing we don't have a specific slot (such as vod: or slides:) for papers, I added directly the link in the description, just below the authors. For example:

--

>     - name: 'Risk Assessment in IoT Case Study: Collaborative Robots System'
>       presenter: <a href="speakers/#salim-chehida">Salim Chehida</a>
>       type: session
>       time: 13:45 - 14:05
>       abstract: |
>              <p><strong>Authors:</strong>
>              <ul>
>                   <li>Salim Chehida, Université Grenoble Alpes</li>
>                   <li>Abdelhakim Baouya, Université Grenoble Alpes</li>
>                   <li>Miquel Cantero, Robotnik Automation S.L.L</li>
>                   <li>Paul-Emmanuel Brun, Airbus Defence & Space</li>
>                   <li>Guillemette Massot, Airbus Defence & Space</li>
>              </ul>
>              <strong>Paper:</strong> <a target="_blank" href="http://ceur-ws.org/Vol-2739/paper_1.pdf">CEUR link</a>
>              
>              <strong>Abstract:</strong> Security is one of the crucial challenges in the design and development of IoT applications. 
>              This paper presents an approach that focuses on existing security standards to evaluate and 
>              analyse the potential risks faced by IoT systems. It begins by identifying system assets and 
>              their associated vulnerabilities and threats. A list of security objectives and technical 
>              requirements are then defined to mitigate the risks and build a secure and safe system. 
>              We use our approach to assess risks in the robotic system for supporting the movement of loads 
>              in a warehouse.</p>
>       vod: https://youtu.be/SOJCH-alwjU
>       slides: https://www.slideshare.net/BrainIoT/samiot-risk-assessment-in-iot-case-study-collaborative-robots-system

--
Unfortunately, the result is not what I expected: 
- First I get 2 icons representing 2 links on the agenda following the title of the paper
image

- None of these links work

**To Reproduce**
https://deploy-preview-130--eclipsefdn-events.netlify.app/2020/sam-iot/

Thanks a lot for your help

### PR DESCRIPTION
**Pull request by flora8984461**
Fix #131 

This branch is detached from @phkrief u17 branch

Signed-off-by: Yi Liu <yi.liu@eclipse-foundation.org>

### CODE REVIEW

**Review by chrisguindon — CHANGES_REQUESTED** [review]
please remove packages-lock.json from your PR if you are not changing any of the dependencies.

**Review by chrisguindon — CHANGES_REQUESTED** [review]
Yi, I think you are deleting the file now. We want to keep it, we just don't want to change it!

**Comment by flora8984461** [comment]
> Yi, I think you are deleting the file now. We want to keep it, we just don't want to change it!

Oops, I thought if I removing from the PR it will leave it untouched. Sorry, let me bring it back. I forgot the master is already updated to 106  🤣

**Comment by flora8984461** [comment]
I have updated the font size in the less file, and the view will be good if https://github.com/EclipseFdn/hugo-solstice-theme/pull/189 is merged.

**Pull request merged**
