### PR TITLE
Infra 3708 - Create the SAM IoT 2020 landing page

### PR DESCRIPTION
**Pull request by ericpoirier**
Signed-off-by: Eric Poirier <eric.poirier@eclipse-foundation.org>

### CODE REVIEW

**Comment by chrisguindon** [comment]
@shanda-eclipse are you the owner of this event? 

Who should we expect to give us a +1 for making this page live?

**Comment by shanda-eclipse** [comment]
@annejacko or @Ioana240 can provide approval to go live.

**Comment by chrisguindon** [comment]
@shanda-eclipse Thanks! 

I think it will be important that these details are included in the issue when an event is requested since my team will not be aware of who is doing what for each event!

 @annejacko @Ioana240 Could you tell what change we need to do before we can make this! 
https://deploy-preview-11--eclipsefdn-events.netlify.app/2020/sam-iot/

**Comment by annejacko** [comment]
@chrisguindon @Ioana240 I just heard today that there is some discussion about the scheduling of this event, since we have three events we are supporting that week, and some are overlapping. So we should hold off on making it live until that's settled.

**Pull request merged**
