### PR TITLE
add speaker bio page

### PR DESCRIPTION
**Pull request by chrisguindon**
Signed-off-by: Christopher Guindon <chris.guindon@eclipse-foundation.org>

### CODE REVIEW

**Comment by sjkiwai** [comment]
Hi Chris,
Thank you for doing this! Two suggestions - 
1 - Can we change the title of the section to be "Keynote" and add the title as the subheader?
Title: Cobbles and Potholes – On the Bumpy Road to Secure Software Supply Chains

2 - And, could we add the abstract to the description page as well?  

Abstract: Open source software is ubiquitous – all across the stack, in the cloud and on-premise, on all devices, in commercial and non-commercial offerings. This success, the dependency of the software industry on open source, combined with recent data breaches and attacks, puts security into the spotlight. This talk will provide an overview - for sure opinionated, hopefully controversial – about the state of affairs and current trends regarding the security of software supply chains, both from consumer and producer perspective.

Let me know what you think!
Susan

**Comment by chrisguindon** [comment]
@sjkiwai I made the change to the title! I am also working on a patch to make the text optional in the keynote section of the page: https://github.com/EclipseFdn/hugo-solstice-theme/pull/143/files

In regards to the abstract, I would expect that to go in the agenda.

**Comment by chrisguindon** [comment]
I made some changes to the keynote section:
https://deploy-preview-56--eclipsefdn-events.netlify.app/2020/sam-iot/#keynote

@sjkiwai @phkrief please let me know what you think!

**Comment by phkrief** [comment]
Looks great!!!

**Comment by chrisguindon** [comment]
@phkrief Do you want us to go live as-is or do you wish to make more changes?

**Comment by sjkiwai** [comment]
@chrisguindon 
Let's go ahead with this change. Philippe is on vacation and I don't know how often he's reading mails. If we need to update later this week, we can do it then. I might try to add title and abstract for the keynote to the subpage.

**Pull request merged**
